apiVersion: v2
name: grafana
version: 7.3.11
appVersion: 10.4.1
kubeVersion: "^1.8.0-0"
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.com
icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
sources:
  - https://github.com/ganeshcpote/monitoring-helm-chart/grafana
  - https://github.com/ganeshcpote/monitoring-helm-chart
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/ganeshcpote/monitoring-helm-chart
    - name: Upstream Project
      url: https://github.com/ganeshcpote/monitoring-helm-chart/grafana
maintainers:
  - name: ganeshpote
    email: ganesh.c.pote@gmail.com
type: application
keywords:
  - monitoring
  - metric
